WITH 
CONFIG AS 
(
    SELECT
        TO_DATE('01/01/2026', 'DD/MM/YYYY') AS DT_INI,
        TO_DATE('31/12/2026', 'DD/MM/YYYY') AS DT_FIM
    FROM DUAL
),

EMPRESAS AS 
(
    SELECT 1 AS CD_EMPRESA FROM DUAL UNION ALL
    SELECT 5 FROM DUAL UNION ALL
    SELECT 6 FROM DUAL UNION ALL
	SELECT 7 FROM DUAL UNION ALL
	SELECT 14 FROM DUAL UNION ALL
	SELECT 19 FROM DUAL
),

PARAMS AS 
(
    SELECT 
	C.DT_INI, 
	C.DT_FIM, 
	E.CD_EMPRESA
	
    FROM 
	CONFIG C, 
	EMPRESAS E
),


CONTADOR AS 
(
    SELECT 
        C.DT_INI - 1 + ROWNUM AS DATA
    FROM 
        DBAMV.CID,
        CONFIG C          -- ← usar CONFIG em vez de PARAMS
    WHERE 
        C.DT_INI - 1 + ROWNUM <= C.DT_FIM
)

SELECT
	CD_MULTI_EMPRESA,
	DT_REFERENCIA,
    CD_UNID_INT,
    CD_ESPECIALID,
	CD_ORI_ATE,
	TP_ATENDIMENTO,
    SUM(PAC_INT_00H) AS PAC_INT_00H,
    SUM(ENT_INTERNADOS) AS ENT_INTERNADOS,
    SUM(ENT_TRANSF) AS ENT_TRANSF,
    SUM(SAI_ALTAS) AS SAI_ALTAS,
    SUM(SAI_TRANSFPARA) AS SAI_TRANSFPARA,
    SUM(SAI_OBITOS) AS SAI_OBITOS,
    SUM(SAI_OBITOS48) AS SAI_OBITOS48,
    SUM(SAI_OBITOS24) AS SAI_OBITOS24,
    SUM(HOSP_DIA) AS HOSP_DIA,
    SUM(OBITO_DIA) AS OBITO_DIA,
    (SUM(NVL(PAC_INT_00H,0)) + SUM(NVL(ENT_INTERNADOS,0)) + SUM(NVL(ENT_TRANSF,0))) -
    (SUM(NVL(SAI_ALTAS,0))   + SUM(NVL(SAI_TRANSFPARA,0)) + SUM(NVL(SAI_OBITOS,0))) AS PAC_DIA

FROM 
(
    -- PACIENTES INTERNADOS ATE AS 0:00H
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        COUNT(*) AS PAC_INT_00H,
        0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF, 
		0 AS SAI_ALTAS,
        0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,  
		0 AS SAI_OBITOS48,
        0 AS SAI_OBITOS24,   
		0 AS HOSP_DIA,    
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.MOV_INT MI
		JOIN DBAMV.ATENDIME A   
		ON A.CD_ATENDIMENTO = MI.CD_ATENDIMENTO
		
		JOIN DBAMV.LEITO L  
		ON L.CD_LEITO = MI.CD_LEITO
		
		JOIN DBAMV.UNID_INT UI  
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO C   
		ON C.CD_CONVENIO = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E   
		--ON E.CD_ESPECIALID  = A.CD_ESPECIALID
		
		JOIN PARAMS  P   
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR CT  
		ON TRUNC(MI.DT_MOV_INT) <= CT.DATA - 1
		AND TRUNC(NVL(MI.DT_LIB_MOV, SYSDATE))  >  CT.DATA - 1
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
	
    WHERE 
		MI.TP_MOV  IN ('O', 'I')
		 AND A.TP_ATENDIMENTO IN ('I', 'H', 'U')
		 AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
	  
    GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- ENTRADAS DE PACIENTES INTERNADOS NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		COUNT(*) AS ENT_INTERNADOS,
        0 AS ENT_TRANSF,    
		0 AS SAI_ALTAS,   
		0 AS SAI_TRANSFPARA,
        0 AS SAI_OBITOS,    
		0 AS SAI_OBITOS48, 
		0 AS SAI_OBITOS24,
        0 AS HOSP_DIA,      
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.MOV_INT        MI
		JOIN DBAMV.ATENDIME        A   
		ON A.CD_ATENDIMENTO  = MI.CD_ATENDIMENTO
		
		JOIN DBAMV.LEITO           L   
		ON L.CD_LEITO        = MI.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI  
		ON UI.CD_UNID_INT    = L.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO        C   
		ON C.CD_CONVENIO     = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E   
		--ON E.CD_ESPECIALID   = A.CD_ESPECIALID
		
		JOIN PARAMS                P   
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT  
		ON TRUNC(MI.DT_MOV_INT) = TRUNC(CT.DATA)
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
	
    WHERE 
		MI.TP_MOV          = 'I'
		  AND A.TP_ATENDIMENTO   IN ('I', 'H', 'U')
		  AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
		  AND NOT EXISTS 
		  (
			  SELECT 
				'X' 
			  
			  FROM 
				DBAMV.MOV_INT MI2
			  
			  WHERE 
				  MI2.CD_ATENDIMENTO = MI.CD_ATENDIMENTO
				  AND TO_DATE(TO_CHAR(MI2.DT_MOV_INT,'DD/MM/YYYY') || TO_CHAR(MI2.HR_MOV_INT,'HH24:MISS'), 'DD/MM/YYYYHH24:MISS')
					  < TO_DATE(TO_CHAR(MI.DT_MOV_INT,'DD/MM/YYYY')  || TO_CHAR(MI.HR_MOV_INT,'HH24:MISS'),  'DD/MM/YYYYHH24:MISS')
				  AND MI2.CD_LEITO       = MI.CD_LEITO
				  AND MI2.CD_TIP_ACOM   <> MI.CD_TIP_ACOM
				  AND NVL(MI2.CD_LEITO_ANTERIOR, MI2.CD_LEITO) = NVL(MI.CD_LEITO_ANTERIOR, MI.CD_LEITO)
		  )
    GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- ENTRADAS DE PACIENTES TRANSFERIDOS NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS,
        COUNT(*) AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,
        0 AS SAI_OBITOS48,  
		0 AS SAI_OBITOS24,   
		0 AS HOSP_DIA,
        0 AS OBITO_DIA
		
    FROM DBAMV.MOV_INT        MI
		JOIN DBAMV.ATENDIME        A   
		ON A.CD_ATENDIMENTO   = MI.CD_ATENDIMENTO
		
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO         = MI.CD_LEITO
		
		JOIN DBAMV.LEITO           L1   
		ON L1.CD_LEITO        = MI.CD_LEITO_ANTERIOR
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT     = L.CD_UNID_INT
		
		JOIN DBAMV.UNID_INT        UI1  
		ON UI1.CD_UNID_INT    = L1.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO      = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID    = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(MI.DT_MOV_INT) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
	
    WHERE 
		MI.TP_MOV          = 'O'
		  AND UI.CD_UNID_INT    <> UI1.CD_UNID_INT
		  AND A.TP_ATENDIMENTO   IN ('I', 'H', 'U')
		  AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
		  AND NOT EXISTS 
		  (
			  SELECT 
				'X' 
			  
			  FROM 
				DBAMV.MOV_INT MI2
			  
			  WHERE 
				MI2.CD_ATENDIMENTO = MI.CD_ATENDIMENTO
				AND TO_DATE(TO_CHAR(MI2.DT_MOV_INT,'DD/MM/YYYY') || TO_CHAR(MI2.HR_MOV_INT,'HH24:MISS'), 'DD/MM/YYYYHH24:MISS')
				< TO_DATE(TO_CHAR(MI.DT_MOV_INT,'DD/MM/YYYY')  || TO_CHAR(MI.HR_MOV_INT,'HH24:MISS'),  'DD/MM/YYYYHH24:MISS')
				AND MI2.CD_LEITO       = MI.CD_LEITO
				AND MI2.CD_TIP_ACOM   <> MI.CD_TIP_ACOM
				AND NVL(MI2.CD_LEITO_ANTERIOR, MI2.CD_LEITO) = NVL(MI.CD_LEITO_ANTERIOR, MI.CD_LEITO)
		  )
	  
    GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- SAIDAS DE PACIENTES EM ALTA NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        COUNT(*) AS SAI_ALTAS,
        0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,    
		0 AS SAI_OBITOS48,
        0 AS SAI_OBITOS24,   
		0 AS HOSP_DIA,       
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.ATENDIME        A
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO      = A.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO   = A.CD_CONVENIO
		
		LEFT JOIN DBAMV.MOT_ALT         MA   
		ON MA.CD_MOT_ALT   = A.CD_MOT_ALT
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(A.DT_ALTA) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
    
	WHERE 
		(MA.TP_MOT_ALTA     <> 'O' OR MA.TP_MOT_ALTA IS NULL)
		AND A.TP_ATENDIMENTO    IN ('I', 'U')
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
    
	GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- SAIDAS DE PACIENTES TRANSFERIDOS PARA OUTRAS UNIDADES NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		COUNT(*) AS SAI_TRANSFPARA,
        0 AS SAI_OBITOS,    
		0 AS SAI_OBITOS48,   
		0 AS SAI_OBITOS24,
        0 AS HOSP_DIA,      
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.MOV_INT        MI
		JOIN DBAMV.ATENDIME        A    
		ON A.CD_ATENDIMENTO   = MI.CD_ATENDIMENTO
		
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO         = MI.CD_LEITO_ANTERIOR
		
		JOIN DBAMV.LEITO           L1   
		ON L1.CD_LEITO        = MI.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT     = L.CD_UNID_INT
		
		JOIN DBAMV.UNID_INT        UI1  
		ON UI1.CD_UNID_INT    = L1.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO      = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID    = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(MI.DT_MOV_INT) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
    
	WHERE 
		MI.TP_MOV          = 'O'
		AND UI.CD_UNID_INT    <> UI1.CD_UNID_INT
		AND A.TP_ATENDIMENTO   IN ('I', 'H', 'U')
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
		AND NOT EXISTS
		(
		SELECT 
		'X' 
		
		FROM 
		DBAMV.MOV_INT MI2
		
		WHERE 
		MI2.CD_ATENDIMENTO = MI.CD_ATENDIMENTO
		AND TO_DATE(TO_CHAR(MI2.DT_MOV_INT,'DD/MM/YYYY') || TO_CHAR(MI2.HR_MOV_INT,'HH24:MISS'), 'DD/MM/YYYYHH24:MISS')
		< TO_DATE(TO_CHAR(MI.DT_MOV_INT,'DD/MM/YYYY')  || TO_CHAR(MI.HR_MOV_INT,'HH24:MISS'),  'DD/MM/YYYYHH24:MISS')
		AND MI2.CD_LEITO       = MI.CD_LEITO
		AND MI2.CD_TIP_ACOM   <> MI.CD_TIP_ACOM
		AND NVL(MI2.CD_LEITO_ANTERIOR, MI2.CD_LEITO) = NVL(MI.CD_LEITO_ANTERIOR, MI.CD_LEITO)
		
		)
    GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- SAIDAS DE PACIENTES COM OBITOS NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA,
        COUNT(*) AS SAI_OBITOS,
        0 AS SAI_OBITOS48,  
		0 AS SAI_OBITOS24,
        0 AS HOSP_DIA,      
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.ATENDIME        A
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO      = A.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.MOT_ALT         MA   
		ON MA.CD_MOT_ALT   = A.CD_MOT_ALT
		
		LEFT JOIN DBAMV.CONVENIO   C    
		ON C.CD_CONVENIO   = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(A.DT_ALTA) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
    
	WHERE 
		MA.TP_MOT_ALTA     = 'O'
		AND A.TP_ATENDIMENTO   IN ('I', 'U')
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
		
	GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- SAIDAS DE PACIENTES COM OBITOS COM MAIS DE 24 HORAS NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,
        COUNT(*) AS SAI_OBITOS48,
        0 AS SAI_OBITOS24,  
		0 AS HOSP_DIA,       
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.ATENDIME        A
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO      = A.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.MOT_ALT         MA   
		ON MA.CD_MOT_ALT   = A.CD_MOT_ALT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO   = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(A.DT_ALTA) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
    
	WHERE 
		MA.TP_MOT_ALTA     = 'O'
		 AND A.TP_ATENDIMENTO   IN ('I', 'U')
		 AND DBAMV.FNC_MV_RECUPERA_DATA_HORA(A.DT_ALTA, A.HR_ALTA)
		- DBAMV.FNC_MV_RECUPERA_DATA_HORA(A.DT_ATENDIMENTO, A.HR_ATENDIMENTO) > 1
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
    
	GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- SAIDAS DE PACIENTES COM OBITOS COM ATE 24 HORAS NO PERIODO
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,
        0 AS SAI_OBITOS48,  
		COUNT(*) AS SAI_OBITOS24,
        0 AS HOSP_DIA,      
		0 AS OBITO_DIA
		
    FROM 
		DBAMV.ATENDIME        A
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO      = A.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.MOT_ALT         MA   
		ON MA.CD_MOT_ALT   = A.CD_MOT_ALT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO   = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(A.DT_ALTA) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
   
   WHERE 
		MA.TP_MOT_ALTA     = 'O'
		AND A.TP_ATENDIMENTO   IN ('I', 'U')
		AND DBAMV.FNC_MV_RECUPERA_DATA_HORA(A.DT_ALTA, A.HR_ALTA)
		- DBAMV.FNC_MV_RECUPERA_DATA_HORA(A.DT_ATENDIMENTO, A.HR_ATENDIMENTO) <= 1
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
   
   GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- HOSPITAL DIA (ENTRADA E SAIDA NO MESMO DIA)
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,
        0 AS SAI_OBITOS48,  
		0 AS SAI_OBITOS24,
        COUNT(*) AS HOSP_DIA,
        0 AS OBITO_DIA
		
    FROM 
		DBAMV.MOV_INT        MI
		JOIN DBAMV.ATENDIME        A    
		ON A.CD_ATENDIMENTO  = MI.CD_ATENDIMENTO
		
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO        = MI.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT    = L.CD_UNID_INT
		
		JOIN DBAMV.CONVENIO        C    
		ON C.CD_CONVENIO     = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID   = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(MI.DT_MOV_INT) = CT.DATA
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
    
	WHERE 
		MI.TP_MOV          = 'I'
		AND A.TP_ATENDIMENTO   IN ('I', 'H', 'U')
		AND A.DT_ALTA          IS NOT NULL
		AND TRUNC(A.DT_ATENDIMENTO) = TRUNC(A.DT_ALTA)
		AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
		AND NOT EXISTS 
		(
		SELECT
			'X' 
		FROM 
			DBAMV.MOV_INT MI2
		
		WHERE 
			MI2.CD_ATENDIMENTO = MI.CD_ATENDIMENTO
			AND TO_DATE(TO_CHAR(MI2.DT_MOV_INT,'DD/MM/YYYY') || TO_CHAR(MI2.HR_MOV_INT,'HH24:MISS'), 'DD/MM/YYYYHH24:MISS')
			< TO_DATE(TO_CHAR(MI.DT_MOV_INT,'DD/MM/YYYY')  || TO_CHAR(MI.HR_MOV_INT,'HH24:MISS'),  'DD/MM/YYYYHH24:MISS')
			AND MI2.CD_LEITO       = MI.CD_LEITO
			AND MI2.CD_TIP_ACOM   <> MI.CD_TIP_ACOM
			AND NVL(MI2.CD_LEITO_ANTERIOR, MI2.CD_LEITO) = NVL(MI.CD_LEITO_ANTERIOR, MI.CD_LEITO)
		)
		
    GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
        UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

    UNION

    -- OBITOS DO DIA (ENTRADA E SAIDA POR OBITO NO MESMO DIA)
    SELECT
		A.CD_MULTI_EMPRESA,
		CT.DATA AS DT_REFERENCIA,
		UI.CD_UNID_INT,
        A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO,
        0 AS PAC_INT_00H,   
		0 AS ENT_INTERNADOS, 
		0 AS ENT_TRANSF,
        0 AS SAI_ALTAS,     
		0 AS SAI_TRANSFPARA, 
		0 AS SAI_OBITOS,
        0 AS SAI_OBITOS48,  
		0 AS SAI_OBITOS24,   
		0 AS HOSP_DIA,
        COUNT(*) AS OBITO_DIA
		
    FROM 
		DBAMV.ATENDIME        A
		JOIN DBAMV.LEITO           L    
		ON L.CD_LEITO      = A.CD_LEITO
		
		JOIN DBAMV.UNID_INT        UI   
		ON UI.CD_UNID_INT  = L.CD_UNID_INT
		
		JOIN DBAMV.MOT_ALT         MA   
		ON MA.CD_MOT_ALT   = A.CD_MOT_ALT
		
		JOIN DBAMV.CONVENIO        C   
		ON C.CD_CONVENIO   = A.CD_CONVENIO
		
		--LEFT JOIN DBAMV.ESPECIALID E    
		--ON E.CD_ESPECIALID = A.CD_ESPECIALID
		
		JOIN PARAMS                P    
		ON A.CD_MULTI_EMPRESA = P.CD_EMPRESA
		
		JOIN CONTADOR              CT   
		ON TRUNC(A.DT_ATENDIMENTO) = TRUNC(CT.DATA)
		
		LEFT JOIN PACIENTE PA
		ON A.CD_PACIENTE = PA.CD_PACIENTE
   
   WHERE 
		MA.TP_MOT_ALTA     = 'O'
		AND A.TP_ATENDIMENTO   IN ('I', 'U')
		AND TRUNC(A.DT_ATENDIMENTO) = TRUNC(A.DT_ALTA)
        AND PA.NM_PACIENTE NOT LIKE '%TESTE%'
	
	GROUP BY
		A.CD_MULTI_EMPRESA,
		CT.DATA,
		UI.CD_UNID_INT,
		A.CD_ESPECIALID,
		A.CD_ORI_ATE,
		A.TP_ATENDIMENTO

)

GROUP BY
	CD_MULTI_EMPRESA,
	DT_REFERENCIA,
    CD_UNID_INT,
    CD_ESPECIALID,
	CD_ORI_ATE,
	TP_ATENDIMENTO
	
ORDER BY 
	DT_REFERENCIA